import React from 'react';
import { useParams, useNavigate, Navigate } from 'react-router';
import { ArrowLeft } from 'lucide-react';

const INFO_CONTENT: Record<string, { title: string; subtitle: string; sections: { heading: string; body: React.ReactNode | React.ReactNode[] }[] }> = {
  about: {
    title: 'About VAULTÉ',
    subtitle: "The private members' boutique redefining accessible luxury.",
    sections: [
      {
        heading: 'Our Story',
        body: 'VAULTÉ was founded in 2026 with a singular vision: to give style-conscious consumers access to premium and luxury brands at prices that make sense. By working directly with brands and authorised distributors, we eliminate unnecessary retail markups and pass the savings directly to our members.',
      },
      {
        heading: 'Our Model',
        body: 'Unlike traditional flash-sale sites, VAULTÉ operates on a curated, members-only model. We carefully select over 3,000 designer labels and negotiate exclusive deals that our members can access 24/7 — not just during timed events. Quality over quantity, always.',
      },
      {
        heading: 'Sustainability',
        body: 'By selling premium items at accessible prices rather than seeing them go to landfill, VAULTÉ directly supports a more circular fashion economy. We are committed to reducing packaging waste, offsetting our carbon footprint, and partnering with brands who share our values.',
      },
      {
        heading: 'Our Team',
        body: 'We are a team of 200+ fashion, tech, and logistics professionals based in Munich, Paris, and London. United by a belief that great style should be for everyone.',
      },
    ],
  },
  careers: {
    title: 'Careers at VAULTÉ',
    subtitle: 'Join us in building the future of luxury fashion.',
    sections: [
      {
        heading: 'Why Work With Us?',
        body: 'VAULTÉ offers a dynamic, high-growth environment where your work directly shapes how millions of people experience fashion. We offer competitive salaries, generous employee discounts, flexible working, and a culture built on trust and ambition.',
      },
      {
        heading: 'Open Roles',
        body: (
          <span>
            Check out our open roles and more information on how to apply at{' '}
            <a href="#" className="underline text-black hover:text-gray-700 transition-colors">
              our careers portal
            </a>
            .
          </span>
        ),
      },
    ],
  },
  press: {
    title: 'Press & Media',
    subtitle: 'Media inquiries, brand kit, and editorial coverage.',
    sections: [
      {
        heading: 'Media Contact',
        body: 'For press inquiries, interview requests, and media partnerships, please contact our communications team at press@vaulte.com. We aim to respond within 24 hours.',
      },
      {
        heading: 'Recent Coverage',
        body: [
          '"VAULTÉ is quietly disrupting the luxury flash-sale market." — Business of Fashion',
          '"The members-only model that\'s winning over Gen Z luxury buyers." — Vogue Business',
          '"Best luxury off-price platform of 2025." — Glamour Awards',
        ],
      },
      {
        heading: 'Brand Assets',
        body: 'Our brand kit — including logos, brand guidelines, and press photography — is available upon request to verified media partners. Please contact press@vaulte.com.',
      },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    subtitle: 'How we collect, use, and protect your personal data.',
    sections: [
      {
        heading: 'Data We Collect',
        body: 'We collect information you provide directly (name, email, shipping address, payment details) and data generated by your use of the platform (browsing history, wishlist, order history). Payment card details are never stored on our servers — they are processed via PCI-DSS compliant third-party providers.',
      },
      {
        heading: 'How We Use Your Data',
        body: 'Your data is used to process orders, personalise your shopping experience, send relevant communications (with your consent), and improve our platform. We do not sell your personal data to third parties.',
      },
      {
        heading: 'Your Rights (GDPR)',
        body: 'Under the GDPR, you have the right to access, correct, delete, or export the personal data we hold about you. You may also withdraw consent for marketing communications at any time. To exercise these rights, contact privacy@vaulte.com.',
      },
      {
        heading: 'Cookies',
        body: 'We use essential cookies to operate the site and optional analytics/marketing cookies to improve your experience. You can manage your cookie preferences at any time via the cookie settings link in our footer.',
      },
    ],
  },
  terms: {
    title: 'Terms & Conditions',
    subtitle: 'The legal agreement between you and VAULTÉ.',
    sections: [
      {
        heading: 'Membership',
        body: 'VAULTÉ membership is personal and non-transferable. You must be at least 18 years old to create an account. We reserve the right to suspend or terminate accounts that violate our terms.',
      },
      {
        heading: 'Pricing & Payment',
        body: 'All prices are displayed in Euros and are inclusive of applicable VAT. Prices may change at any time. Your payment is processed at the time of order placement. We accept Visa, Mastercard, PayPal, Apple Pay, and Klarna.',
      },
      {
        heading: 'Delivery & Risk',
        body: 'Risk of loss and title for products pass to you upon delivery to the carrier. Standard delivery takes 4–7 working days. Express delivery (1–2 working days) is available at an additional charge in select destinations.',
      },
      {
        heading: 'Returns',
        body: 'You have a 30-day right of withdrawal from the date of delivery. Items must be returned in their original, unworn condition with all tags attached. Certain items (e.g., underwear with hygiene seals removed) are excluded. Full details are in our Returns Policy.',
      },
    ],
  },
};

export function InfoPage() {
  const { slug } = useParams<{ slug: string }>();
  const navigate = useNavigate();

  if (!slug || !INFO_CONTENT[slug]) {
    return <Navigate to="/" replace />;
  }

  const content = INFO_CONTENT[slug];

  return (
    <div className="min-h-screen bg-[#fafafa]">
      {/* Hero */}
      <div className="bg-[#0a0a0a] text-[#fafafa] py-16 px-6 text-center">
        <h1 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: 42, fontWeight: 300, marginBottom: 12 }}>
          {content.title}
        </h1>
        <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 15, color: 'rgba(250,250,248,0.65)', maxWidth: 540, margin: '0 auto' }}>
          {content.subtitle}
        </p>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 text-[#6b6b6b] hover:text-[#0a0a0a] transition-colors mb-12 focus:outline-none focus:ring-2 focus:ring-[#0a0a0a] rounded-sm pr-2"
          style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 13, fontWeight: 500, background: 'none', border: 'none', cursor: 'pointer' }}
        >
          <ArrowLeft className="w-4 h-4" />
          Go Back
        </button>

        <div className="space-y-12">
          {content.sections.map((section, idx) => (
            <section key={idx} aria-labelledby={`info-section-${idx}`}>
              <h2
                id={`info-section-${idx}`}
                style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 18, fontWeight: 500, color: '#0a0a0a', marginBottom: 16 }}
              >
                {section.heading}
              </h2>
              {Array.isArray(section.body) ? (
                <ul className="space-y-3" style={{ paddingLeft: 0, listStyle: 'none' }}>
                  {section.body.map((item, i) => (
                    <li
                      key={i}
                      className="flex items-start gap-3"
                      style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 15, color: '#4a4a4a', lineHeight: 1.7 }}
                    >
                      <span className="w-1.5 h-1.5 rounded-full bg-[#0a0a0a] shrink-0 mt-2.5" aria-hidden="true" />
                      {item}
                    </li>
                  ))}
                </ul>
              ) : (
                <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 15, color: '#4a4a4a', lineHeight: 1.75 }}>
                  {section.body}
                </p>
              )}
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}